core/urls.py
from unicodedata import name
from django.urls import path
from .views import index, base, familia

urlpatterns = [
    path('', base, name="base"),
    path('index',index, name="index"),
    path('registrar_familia', familia, name="familia")
]

novagestion/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v
from programas import views as vp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
    path("programas/", vp.programas, name="programas"),
    path("publicar_programas", vp.publicar_programas, name="publicar_programas"),
    path("postular_programa/<int:pk>", vp.postular_programa, name="postular_programa"),
    path('', include('core.urls')),
    path('', include("django.contrib.auth.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

programas/urls.py
from unicodedata import name
from django.urls import path
from .views import programas, publicar_programas

urlpatterns = [
    path('programas',programas, name="programas"),
    path('publicar_programas', publicar_programas, name="publicar_programas"),
]

core/models.py
from django.db import models

# Create your models here.

class Familia(models.Model):
    rutJefeFamilia = models.CharField(max_length=9, verbose_name="Rut Jefe Familia: ")
    numIntegrantes = models.IntegerField(verbose_name="N° de integrantes: ")
    direccion = models.CharField(max_length=50 ,verbose_name="Dirección Hogar: ")
    antecedentes = models.ImageField(upload_to="media", blank=True)
    
    def __str__(self):
        return self.rutJefeFamilia

programas/models.py
from django.db import models

# Create your models here.
class Programa(models.Model):
    nombrePrograma = models.CharField(max_length=30, verbose_name="Nombre del programa:")
    localizacion_cel = models.CharField(max_length=30, verbose_name="Localización del CEL:")
    duracion = models.CharField(max_length=30, verbose_name="duración del programa:")
    nombreCEL = models.CharField(max_length=30, verbose_name="Nombre del CEL:")
    vacantes = models.IntegerField(verbose_name="Número de vacantes disponibles:")
    def __str__(self):
        return self.nombrePrograma

class PostularPrograma(models.Model):
    id_postulacion = models.AutoField(primary_key=True)
    id = models.ForeignKey(Programa, on_delete=models.CASCADE, verbose_name="ID del programa: ", null=True, blank=True)
    nombreAlumno = models.CharField(max_length=70, verbose_name="Nombre del alumno: ")
    emailAlumno = models.EmailField(max_length=70, verbose_name="Email del alumno: ")
    motivoPostulacion = models.CharField(max_length=70, verbose_name="Motivo de la postulación: ")
    def __str__(self):
        return self.nombreAlumno

register/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from .models import Familia

class RegistrarFamilia(ModelForm):
    class Meta:
        model = Familia
        fields = ["rutJefeFamilia", "numIntegrantes", "direccion", "antecedentes"] 

programas/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from .models import Programa, PostularPrograma

class PublicarPrograma(ModelForm):
    class Meta:
        model = Programa
        fields = ["nombrePrograma", "localizacion_cel", "duracion", "nombreCEL", "vacantes"]

class PostularPrograma(ModelForm):

    id_postulacion = models.AutoField(primary_key=True)
    id = models.ForeignKey(Programa, on_delete=models.CASCADE)
    class Meta:
        model = PostularPrograma
        fields = ["nombreAlumno", "emailAlumno", "motivoPostulacion"]

register/forms.py
from dataclasses import fields
from django import forms
from django.forms import ModelForm
from django.db import models
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = models.EmailField
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

core/views.py
from django.shortcuts import render, redirect
from .forms import RegistrarFamilia
from .models import Familia

# Create your views here.

def base(response):
    return redirect('index')

def index(request):
    return render (request, 'core/index.html')

def familia(request):

    form = RegistrarFamilia

    if request.method == 'POST':
        form = RegistrarFamilia(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/index')
        else:
            form = RegistrarFamilia()

    context = {"form": form}

    return render(request, 'core/registrar_familia.html', context)

programas/views.py
from django.shortcuts import render, redirect
from multiprocessing import context
from .forms import PublicarPrograma, PostularPrograma
from .models import Programa

# Create your views here.

def programas(request):
    programa = Programa.objects.all()
    context = {'programa': programa}

    return render (request, 'core/programas.html', context)

    
def publicar_programas(request):

    form = PublicarPrograma()

    if request.method == 'POST':
        form = PublicarPrograma(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/programas')
        else:
            form = PublicarPrograma()

    context2 = {'form': form}

    return render (request, 'core/publicar_programas.html', context2)

def postular_programa(request, pk):

    form = PostularPrograma()
    programa = Programa.objects.get(id = pk)

    if request.method == 'POST':
        form = PostularPrograma(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/index')
        else:
            form =  PostularPrograma()

    context = {'form': form, 'programa': programa}

    return render (request, 'core/postular_programa.html', context)

register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm

# Create your views here.

def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
            return redirect("index")
    else:
        form = UserCreationForm()

    return render(response, "register.html", {"form": form})

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> NovaGestion | {% block 'title'%} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/151618a8a2.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}" />
</head>
<body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">N O V A G E S T I O N</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav links">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Nosotros</a>
              </li>
              {% if user.is_anonymous %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Iniciar sesion</a>
              </li>
              {% endif %}
              {% if user.is_superuser%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'publicar_programas' %}">Publicar Programa</a>
              </li>
              {% endif %}
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'programas' %}">Programas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'familia' %}">Subir Antecedentes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    <!-- End Header -->
    {% block 'content' %}
    <!-- all code here -->
    {% endblock %}
    <!-- Footer -->

    <!-- End Footer -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{%block 'title'%} Inicio {%endblock%}

{%block 'content'%}
    {% load static %}
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="https://www.telemundo.com/sites/nbcutelemundo/files/images/article/cover/2019/02/14/joven-universitaria.jpg" class="d-block imgcarrusel" alt="avionvolando">
            <div class="carousel-caption d-none d-md-block">
              <h5>First slide label</h5>
              <p>Some representative placeholder content for the first slide.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="http://www.fonditos3d.com/1920x1080/avion-comercial-3d.jpg" class="d-block imgcarrusel" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>Second slide label</h5>
              <p>Some representative placeholder content for the second slide.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="https://www.infobae.com/new-resizer/kO6U4uwMSk9_gULKRjK-4GgklCA=/992x558/filters:format(webp):quality(85)/s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2018/07/17164302/escala-en-el-aeropuerto-4.jpg" class="d-block imgcarrusel" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>Third slide label</h5>
              <p>Some representative placeholder content for the third slide.</p>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
{% endblock %}

core/templates/core/registrar_familia.html
{% extends 'core/base.html' %}

{%block 'title'%} Registrar Familia {%endblock%}

{%block 'content'%}
    {% load static %}
    <h1 style="text-align: center;">Registro de Familia</h1>

    <div class="contenedor">
        <form action="" method="POST" class="form2">
            {% csrf_token %}
            <tr>
                <th><label for="id_rutJefeFamilia" class="form-label">Rut Jefe Familia: :</label></th>
                <td>               
                  <input type="text" name="rutJefeFamilia" maxlength="9" required id="id_rutJefeFamilia" class="form-control">     
                </td>
              </tr>
              <tr>
                <th><label for="id_numIntegrantes" class="form-label">N° de integrantes: :</label></th>
                <td>
                  <input type="number" name="numIntegrantes" required id="id_numIntegrantes" class="form-control">    
                </td>
              </tr>      
              <tr>
                <th><label for="id_direccion" class="form-label">Dirección Hogar: :</label></th>
                <td>           
                  <input type="text" name="direccion" maxlength="50" required id="id_direccion" class="form-control">             
                </td>
              </tr>  
              <tr>
                <th><label for="id_antecedentes" class="form-label">Antecedentes:</label></th>
                <td>            
                  <input type="file" name="antecedentes" accept="image/*" id="id_antecedentes" class="form-control">
                </td>
              </tr>
            <button type="submit" class="btn btn-primary enviar">Guardar Programa.</button>
        </form> 
{% endblock %}

programas/templates/core/postular_programa.html
{% extends 'core/base.html' %}

{%block 'title'%} Postular Programa {%endblock%}

{%block 'content'%}
    {% load static %}
    
        <h1 style="text-align: center;">Postular a un programa</h1>
        
        <div class="contenedor">
            <form action="" method="POST" class="form2">
                {% csrf_token %}
                <tr>
                    <th>
                        <label for="id_nombreAlumno" class="form-label">Nombre del alumno: </label>
                    </th>
                    <td>         
                      <input type="text" name="nombreAlumno" maxlength="70" required id="id_nombreAlumno" class="form-control">      
                    </td>
                </tr>  
                  <tr>
                    <th>
                        <label for="id_emailAlumno" class="form-label">Email del alumno: :</label>
                    </th>
                    <td>    
                      <input type="email" name="emailAlumno" maxlength="70" required id="id_emailAlumno" class="form-control">
                    </td>
                  </tr>       
                <tr>
                    <th>
                        <label for="id_motivoPostulacion" class="form-label">Motivo de la postulación: :</label></th>
                    <td>                  
                      <input type="text" name="motivoPostulacion" maxlength="70" required id="id_motivoPostulacion" class="form-control">
                    </td>
                </tr>
                
                <button type="submit" class="btn btn-primary enviar">Postular</button>
            </form>
        </div>
{% endblock %}

programas/templates/core/programas.html
{% extends 'core/base.html' %}

{%block 'title'%} Listar Programas {%endblock%}

{%block 'content'%}
    {% load static %}
    
    <h1 style="text-align: center;">Listado de Programas</h1>

        
        {% for i in programa %}
            <div class="programa">
                <h3>{{ i.nombrePrograma }}</h3> <br>
                <p>Ciudad de localización: {{ i.localizacion_cel }}</p>
                <p>Duración programa (días): {{ i.duracion }}</p>
                <p>Centro de estudios local: {{ i.nombreCEL }}</p>
                <p>Vacantes: {{ i.vacantes }}</p>
                {% if user.is_authenticated %}
                <a href="{% url 'postular_programa' i.id %}"><button type="submit" class="btn btn-success enviar">Postular</button>
                </a>
                {% endif %}
            </div>
        {% endfor %}
        
{% endblock %}

programas/templates/core/publicar_programas.html
{% extends 'core/base.html' %}

{%block 'title'%} Publicar Programas {%endblock%}

{%block 'content'%}
    {% load static %}
    
        <h1 style="text-align: center;">Publicar un programa</h1>
        
        <div class="contenedor">
            <form action="" method="POST" class="form2">
                {% csrf_token %}
            <tr>
                <th>
                    <label for="id_nombrePrograma" class="form-label">Nombre del programa:</label>
                </th>
                <td>
                    <input type="text" name="nombrePrograma" maxlength="30" required id="id_nombrePrograma" class="form-control">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_localizacion_cel" class="form-label">Localización del CEL:</label>
                </th>
                <td>
                    <input type="text" name="localizacion_cel" maxlength="30" required id="id_localizacion_cel" class="form-control">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_duracion" class="form-label">Duración del programa:</label>
                </th>
                <td>
                    <input type="text" name="duracion" maxlength="30" required id="id_duracion" class="form-control">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_nombreCEL" class="form-label">Nombre del CEL:</label>
                </th>
                <td>
                    <input type="text" name="nombreCEL" maxlength="30" required id="id_nombreCEL" class="form-control">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_vacantes" class="form-label">Número de vacantes disponibles:</label>
                </th>
                <td>
                    <input type="number" name="vacantes" required id="id_vacantes" class="form-control">
                </td>
            </tr>
                
                <button type="submit" class="btn btn-primary enviar">Guardar Programa.</button>
            </form>
        </div>
{% endblock %}

register/templates/register.html
{% extends 'core/base.html' %}

{% block 'title'%} Registro {%endblock%}

{% load crispy_forms_tags %}

{% block 'content'%} 
    {% load static %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        
        <div class="col">
            <form action="" method="POST" class="form-group">
                {% csrf_token%}
                {{ form|crispy }} <br>
                <button class="btn btn-success" type="submit"> Register </button>
            </form>
        </div>
        
        <div class="col"></div>
    </div>
</div>

{%endblock%}